#!/bin/bash
#
# yasp - Yet Another Simple/Speedy Piuparts
#
# 2013 Hideki Yamane <henrich@debian.or.jp>
# 
#-------------------------------------------------------------------------------

set -e

export LANG=C
export LC_ALL=C

if [ ! -z `uname -o | grep Linux` ]; then
    kernel="Linux"
    echo "kernel: Linux"
    echo ""
elif [ ! -z `uname -o | grep BSD` ]; then
    kernel="BSD"
    echo "kernel: *BSD"
    echo "it doesn't support aufs, aborting..."
    exit 1
else
    echo "kernel: unknown, aborting..."
    exit 1
fi

#FIXME: kFreeBSD support?
if [ "$kernel" = Linux ]; then
    config="/boot/config-`uname -a|cut -d' ' -f3`"
else
    exit 1
fi

if [ -z `grep CONFIG_AUFS_FS $config` ]; then
     echo "Your kernel seems to not support aufs, aborting..."
     exit 1
fi

#-------------------------------------------------------------------------------
# read configuration
#-------------------------------------------------------------------------------

if [ -f /etc/yasp.conf ]; then
    . /etc/yasp.conf
fi


if [ -z "$yasp_dir" -o -z "$distro" -o -z "$mirror" ]; then
   echo "Something wrong with configuration... check your yasp.conf"
   exit 1
fi


create()
{
#-------------------------------------------------------------------------------
# prepare directories
#-------------------------------------------------------------------------------
for i in $distro
do
  if [ ! -d "$yasp_dir"/base/"$i" ]; then
      mkdir -p "$yasp_dir"/base/"$i"
  fi
  if [ ! -d "$yasp_dir"/aptcache/"$i"/var/cache/apt/archives ]; then
      mkdir -p "$yasp_dir"/aptcache/"$i"/var/cache/apt/archives
  fi
done

if [ ! -d "$yasp_dir"/aptcache/host/var/cache/apt ]; then
   mkdir -p "$yasp_dir"/aptcache/host/var/cache/apt
fi

if [ ! -f "$yasp_dir"/aptcache/host/var/cache/apt/archives ]; then
    (cd "$yasp_dir"/aptcache/host/var/cache/apt; ln -s /var/cache/apt/archives archives)
fi

for dir in working mountdir failed
do
  if [ ! -d "$yasp_dir"/"$dir" ]; then
      mkdir "$yasp_dir"/"$dir"
  fi
done

#-------------------------------------------------------------------------------
# create base cow: use files if it exists, -P = base.tgz, -C = base.cow
#-------------------------------------------------------------------------------

if [ -d "$basecow" -o "$2" = -C ]; then
  basedistro=`cat /var/cache/pbuilder/base.cow/etc/apt/sources.list | head -n1 |cut -d' ' -f3`
  if [ ! -d "$yasp_dir"/base/"$basedistro"/etc ]; then
      cp -arp "$basecow"/* "$yasp_dir"/base/"$basedistro"
  fi
elif [ -f "$basetgz" -o "$2" = -P ]; then
  basedistro=`cat `tar xvf "$basetgz" etc/apt/sources.list` |head -n1 |cut -d' ' -f3`
  if [ ! -d "$yasp_dir"/base/"$basedistro"/etc ]; then
      tar -C "$yasp_dir"/base/"$basedistro" -xf "$basetgz" 
  fi
fi
}

base_update()
{
for i in $distro
do
  if [ -d "$yasp_dir"/base/"$i"/etc ]; then
      chroot "$yasp_dir"/base/"$i" apt-get -qq update
      chroot "$yasp_dir"/base/"$i" apt-get -dyqq upgrade
  else
      debootstrap "$i" "$yasp_dir"/base/"$i" "$mirror"
  fi
done
}


case "$1" in
    init)
    create
    base_update
    ;;

    base-update)
    base_update
    ;;

#-------------------------------------------------------------------------------
    test)

# get package name from changes file, e.g. hail_0.8+0.11.37389dbf9b-1_amd64.changes
#FIXME: now yasp can only accept .changes file, however probably user want to test .debs

packagefile=`echo $2|grep .changes$`
srcpackage=`echo $2|cut -d'_' -f1`

if [ -z "$packagefile" ]; then
    echo "Please specify .changes file"
    exit 1
else
    package=`cat $packagefile | cut -d' ' -f4|grep .deb$|sort|uniq|cut -d'_' -f1`
fi

# cache *.deb to aptcache

for i in $distro
do
    chroot "$yasp_dir"/base/"$i" apt-get -qq update
    if [ ! -z "$package" ]; then
      for p in $package
      do
          exec_date=`date +%Y%m%d%H%M%S`
          tmpmountdir=`mktemp -d --tmpdir="$yasp_dir"/mountdir --suffix=_"$p"_"$i"_"$exec_date" yaspXXXXX`
          mount -t aufs -o br="$yasp_dir"/aptcache/"$i":"$yasp_dir"/base/"$i"=ro:"$yasp_dir"/aptcache/host=ro none "$tmpmountdir"
	  set +e
          pkgcheck=`chroot "$yasp_dir"/base/"$i" apt-cache show -q "$p" 2>&1`
          set -e
	  if [ ! "$pkgcheck" = "E: No packages found" ]; then
              echo "caching .deb files..."
              chroot "$tmpmountdir" apt-get -dyqq install "$p"
          fi
          umount "$tmpmountdir" && rmdir "$tmpmountdir"
      done
    fi
done


packagelist=`cat "$packagefile" |cut -d' ' -f4|grep .deb$|sort|uniq`
for i in $distro
do
        cp -f "$packagelist" "$yasp_dir"/aptcache/"$i"/var/cache/apt/archives/
	workdir=`mktemp -d --tmpdir "$yasp_dir"/working --suffix=_"$srcpackage"_"$i"_"$exec_date" yaspXXXXX`
        tmpmountdir=`mktemp -d --tmpdir "$yasp_dir"/mountdir --suffix=_"$srcpackage"_"$i"_"$exec_date" yaspXXXXX`
        mount -t -o aufs br="$workdir":"$yasp_dir"/aptcache/"$i"=ro:"$yasp_dir"/base/"$i"=ro:"$yasp_dir"/aptcache/host=ro none "$tmpmountdir"
	mount --bind /proc "$yasp_dir"/mountdir/"$tmpmountdir"/proc
	mount --bind /dev/pts "$yasp_dir"/mountdir/"$tmpmountdir"/dev/pts

	# inside chroot
	chroot "$tmpmountdir"
	set +e
	cd /var/cache/apt/archives/; dpkg -i "$packagelist"
	set -e
	apt-get -fy install

	# throw chroot away...
	exit
	umount "$yasp_dir"/mountdir/"$tmpmountdir"/proc
	umount "$yasp_dir"/mountdir/"$tmpmountdir"/dev/pts
	umount "$yasp_dir"/mountdir/"$tmpmountdir"
done
    ;;
#-------------------------------------------------------------------------------

    help | *)
    cat << END 
    Usage: yasp (init|base-update|test <changes file> |help)

    Option:
      init        : create COW base environment for each distribution
      base-update : update COW base environment for each distribution
      test        : specify changes file and exec test
                    (install/uninstall/remove/purge/uninstall)
      help        : show this message
END

    ;;
esac

