#!/bin/sh

yasp_remove()
{
  workdir_remove=`mktemp -d --tmpdir="$yasp_dir"/working --suffix=_remove_"$i"_"$exec_date" ${srcpackage}XXXXX`
  mount -o remount,ins:0:"$workdir_remove" "$tmpmountdir" > /dev/null

  lst_diff=`mktemp --tmpdir=/tmp ${i}-${srcpackage}XXXXX`
  diff -u "$lst_before" "$lst_after"|grep '^+'|cut -f1|sed -e s/^+// -e s/:"$ARCH"// -e s%^++\ */tmp/.*%% > "$lst_diff"
  if [  -s "$lst_diff" ]; then
	cp "$lst_diff" "$tmpmountdir"/tmp
  	echo -e "${start_yellow}REMOVE${end_color}: remove package(s)..."
  	chroot "$tmpmountdir" apt-get -yqq remove `cat $lst_diff` > /dev/null
  	mount -o remount,del:"$workdir_remove" "$tmpmountdir" > /dev/null
	echo -e "${start_green}Done${end_color}"
  else
	echo "cannot generate package list... aborting."
	# if you would specify exit 1, it returns 0
	exit
  fi
}
