#!/bin/bash

yasp_create()
{
for i in $distro
do
  if [ ! -d "$yasp_dir"/base/"$i" ]; then
      mkdir -p "$yasp_dir"/base/"$i"
  fi
  if [ ! -d "$yasp_dir"/aptcache/"$i"/var/cache/apt/archives ]; then
      mkdir -p "$yasp_dir"/aptcache/"$i"/var/cache/apt/archives
  fi
done

if [ ! -d "$yasp_dir"/aptcache/host/var/cache/apt ]; then
   mkdir -p "$yasp_dir"/aptcache/host/var/cache/apt
fi

if [ ! -h "$yasp_dir"/aptcache/host/var/cache/apt/archives ]; then
    (cd "$yasp_dir"/aptcache/host/var/cache/apt; ln -sf /var/cache/apt/archives archives)
fi

for dir in working mountdir failed
do
  if [ ! -d "$yasp_dir"/"$dir" ]; then
      mkdir "$yasp_dir"/"$dir"
  fi
done

#-------------------------------------------------------------------------------
# create base cow: use files if it exists, -P = base.tgz, -C = base.cow
#-------------------------------------------------------------------------------
if [ -d "$basecow" -o "$2" = -C ]; then
  basedistro=`cat /var/cache/pbuilder/base.cow/etc/apt/sources.list | head -n1 |cut -d' ' -f3`
  if [ ! -d "$yasp_dir"/base/"$basedistro"/etc ]; then
      cp -arp "$basecow"/* "$yasp_dir"/base/"$basedistro"
  fi
elif [ -f "$basetgz" -o "$2" = -P ]; then
  basedistro=`cat `tar xvf "$basetgz" etc/apt/sources.list` |head -n1 |cut -d' ' -f3`
  if [ ! -d "$yasp_dir"/base/"$basedistro"/etc ]; then
      tar -C "$yasp_dir"/base/"$basedistro" -xf "$basetgz"
  fi
fi
}
