#!/bin/sh

yasp_upgrade()
{
  if [ /usr/lib/yasp/yasp_chroot_throw ]; then
          . /usr/lib/yasp/yasp_chroot_throw
  fi
  yasp_chroot_throw

  if [ -z $not_upgrade ]; then
      workdir_upgrade=`mktemp -d --tmpdir="$yasp_dir"/working --suffix=_upgrade_"$i"_"$exec_date" ${srcpackage}XXXXX`
      mount -o remount,ins:0:"$workdir_upgrade" "$tmpmountdir" > /dev/null
      cp -f $packagelist "$tmpmountdir"/tmp/
      echo -e "${start_yellow}UPGRADE${end_color}: upgrade package(s)..."
      set +e
      for pkg in $packagelist
      do
        chroot "$tmpmountdir" dpkg -i /tmp/"$pkg"
      done
      set -e
      chroot "$tmpmountdir" apt-get -fyqq install > /dev/null
      mount -o remount,del:"$workdir_upgrade" "$tmpmountdir"
  fi
}
