#!/bin/sh

yasp_purge()
{
  workdir_purge=`mktemp -d --tmpdir="$yasp_dir"/working --suffix=_purge_"$i"_"$exec_date" ${srcpackage}XXXXX`
  mount -o remount,ins:0:"$workdir_purge" "$tmpmountdir" > /dev/null
  echo -e "${start_yellow}PURGE${end_color}: purge package(s)..."
  # $lst_diff was difined in yasp_remove
  chroot "$tmpmountdir" dpkg --purge `cat $lst_diff` > /dev/null
  mount -o remount,del:"$workdir_purge" "$tmpmountdir" > /dev/null
  echo -e "${start_green}Done${end_color}"
}
