#!/bin/sh

# throw chroot away... catch exit signal as 0 (only, if you would specify 1 or so)
yasp_chroot_throw()
{
trap 'for mountd in "$tmpmountdir"/dev/pts "$tmpmountdir"/proc "$tmpmountdir"; \
      do umount $mountd; done; \
      for directory in "$workdir_install" "$workdir_remove" "$workdir_purge" "$workdir_upgrade"; \
      do if [ -d $directory ]; then rm -rf $directory; fi; done; \
      echo -e "${start_red}`mount|grep aufs`${end_color}"' EXIT
}
