#!/bin/sh

yasp_upgrade()
{
  if [ /usr/lib/yasp/yasp_chroot_throw ]; then
          . /usr/lib/yasp/yasp_chroot_throw
  fi
  yasp_chroot_throw

  if [ ! ${i} = sid ]; then
	  echo -e "${start_yellow}Target is not unstable (sid) but ${distro}. Skipping...${end_color}"
	  exit
  fi
  if [ ! -z $not_upgrade ]; then
	  echo -e "${start_yellow}Specified to skip UPGRADE test. Skipping...${end_color}"
	  exit
  fi

  if dpkg --compare-versions ${pkg_version} gt-nl ${repo_version} ; then
      workdir_upgrade=`mktemp -d --tmpdir="$yasp_dir"/working --suffix=_upgrade_"$i"_"$exec_date" ${srcpackage}XXXXX`
      mount -o remount,ins:0:"$workdir_upgrade" "$tmpmountdir" > /dev/null
      cp -f $packagelist "$tmpmountdir"/tmp/
      echo -e "${start_yellow}UPGRADE${end_color}: upgrade package(s)..."
      set +e
      for pkg in $packagelist
      do
        chroot "$tmpmountdir" dpkg -i /tmp/"$pkg"
      done
      set -e
      chroot "$tmpmountdir" apt-get -fyqq install > /dev/null
      mount -o remount,del:"$workdir_upgrade" "$tmpmountdir"
      echo -e "${start_green}Done${end_color}"
  else
      echo -e "Package version ${repo_version} (in ${distro})"
      echo -e "Package vesrion ${pkg_version} (now you test)"
      echo -e "${pkg_version} =< ${repo_version}"
      echo -e "${start_yellow}Skipping UPGRADE test...${end_color}"
  fi
}
